spring:
  datasource:
    # TODO 注意修改为自己的DB
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/cn/mb/excelexport/dao/mapper/*.xml

# 导出目录
export:
  dir: "D:/test/"
